file:
  uploadMIMEWhiteList: "image/jpeg"
  uploadMimeBlackList: ""
  hashCodeValidate: "MD5"
  upload-suffix-black-list: ""
  upload-suffix-white-list: ""
spring:
  servlet:
    multipart:
      max-file-size: 100MB